server:
  port: 8099

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8088
          predicates:
            - Path=/api/**

# 日志级别 最低 trace
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-shierApi-backend-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
